#!/usr/bin/env python3
"""
scale_ingredients.py — Auto-generates scaled ingredient tables from YAML frontmatter.

Usage:
  python scale_ingredients.py dishes/YYYY-MM-DD-dish.md [...]
  python scale_ingredients.py --all          # process all dishes/
  python scale_ingredients.py --dry-run ...  # print diff, don't write

Scale types:
  linear    — scales proportionally (default)
  discrete  — rounds to nearest integer, minimum 1 (eggs, cloves, whole veg)
  to_taste  — renders as 适量 regardless of multiplier
  fixed     — renders unchanged regardless of multiplier (pan size, etc.)

Generated block is delimited by sentinel comments and replaced on re-run.
"""

import re
import sys
import yaml
from pathlib import Path
from datetime import date

# ---------------------------------------------------------------------------
# Scale targets: (multiplier, label, servings_label)
# Base is 2 servings.
# ---------------------------------------------------------------------------
SCALES = [
    (0.25, "¼x",   "½人份"),
    (0.5,  "½x",   "1人份"),
    (1.0,  "1x",   "2人份 ✦"),
    (1.5,  "1½x",  "3人份"),
    (2.0,  "2x",   "4人份"),
    (2.5,  "2½x",  "5人份"),
]
BASE_IDX = 2  # index of the 1x column

# Nice fraction lookup: float value → display string
FRACTIONS = {
    0.25: "¼",  0.5: "½",  0.75: "¾",
    1.25: "1¼", 1.5: "1½", 1.75: "1¾",
    2.25: "2¼", 2.5: "2½", 2.75: "2¾",
    3.25: "3¼", 3.5: "3½", 3.75: "3¾",
    4.5: "4½",  5.5: "5½",
}

SENTINEL_START = "<!-- SCALED_TABLE:START — do not edit this block manually -->"
SENTINEL_END   = "<!-- SCALED_TABLE:END -->"


# ---------------------------------------------------------------------------
# Number formatting
# ---------------------------------------------------------------------------

def float_to_display(v: float) -> str:
    """Convert a float to a human-readable amount string."""
    if v <= 0:
        return "少许"

    # Check nice fractions first
    for fval, fstr in FRACTIONS.items():
        if abs(v - fval) < 0.01:
            return fstr

    # Clean integer?
    if abs(v - round(v)) < 0.01:
        return str(int(round(v)))

    # >= 10: no decimals
    if v >= 10:
        return str(int(round(v)))

    # 1 decimal, strip trailing zero
    return f"{v:.1f}".rstrip("0").rstrip(".")


def format_amount(ing: dict, multiplier: float) -> str:
    """Return the display string for one ingredient at a given multiplier."""
    scale_type = ing.get("scale", "linear")
    unit = ing.get("unit", "")

    if scale_type == "to_taste":
        return "适量"

    if scale_type == "fixed":
        return f"{ing['amount']}{unit}"

    raw = ing["amount"] * multiplier

    if scale_type == "discrete":
        # Snap to nearest 0.5, minimum 0.5
        snapped = max(0.5, round(raw * 2) / 2)
        if snapped == int(snapped):
            return f"{int(snapped)}{unit}"
        # x.5 cases
        whole = int(snapped)
        return (f"½{unit}" if whole == 0 else f"{whole}½{unit}")

    # linear (default)
    return f"{float_to_display(raw)}{unit}"


# ---------------------------------------------------------------------------
# Table generation
# ---------------------------------------------------------------------------

def build_table(ingredients: list, base_servings: int = 2) -> str:
    """Build the full scaled-table markdown block."""
    today = date.today().isoformat()

    # Header row
    header_cells = ["食材"] + [
        f"{label}<br/>({servings})" for _, label, servings in SCALES
    ]
    header_row = "| " + " | ".join(header_cells) + " |"
    sep_row    = "|" + "|".join([":---"] + ["---:"] * len(SCALES)) + "|"

    rows = [header_row, sep_row]

    for ing in ingredients:
        note = ing.get("note", "")
        name_cell = f"**{ing['name']}**" if not note else f"**{ing['name']}** *({note})*"
        cells = [name_cell]
        for i, (mult, _, _) in enumerate(SCALES):
            val = format_amount(ing, mult)
            # Bold the base column
            cells.append(f"**{val}**" if i == BASE_IDX else val)
        rows.append("| " + " | ".join(cells) + " |")

    table_md = "\n".join(rows)

    block = f"""{SENTINEL_START}
<!-- Generated by scale_ingredients.py · {today} -->

## 📐 份量换算

> 自动生成 · 基础份量：{base_servings}人份 · ✦ = 原始食谱
> `discrete` 食材（整颗蔬菜等）已取整至整数；`适量` 食材不参与换算。

{table_md}

{SENTINEL_END}"""
    return block


# ---------------------------------------------------------------------------
# File processing
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> dict | None:
    """Extract and parse YAML frontmatter from a markdown file."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        print(f"    ⚠️  YAML parse error: {e}")
        return None


def inject_table(text: str, block: str) -> str:
    """Replace existing scaled table block, or insert before first ## heading."""
    pattern = re.compile(
        re.escape(SENTINEL_START) + r".*?" + re.escape(SENTINEL_END),
        re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(block, text)

    # No existing block — insert before first ## heading (after frontmatter)
    # Skip past frontmatter first
    fm_end = re.search(r"^---\n.*?\n---\n", text, re.DOTALL)
    search_start = fm_end.end() if fm_end else 0

    first_h2 = re.search(r"^## ", text[search_start:], re.MULTILINE)
    if first_h2:
        insert_at = search_start + first_h2.start()
        return text[:insert_at] + block + "\n\n" + text[insert_at:]

    return text.rstrip() + "\n\n" + block + "\n"


def process_file(path: Path, dry_run: bool = False) -> bool:
    """Process one recipe file. Returns True if file was (or would be) changed."""
    text = path.read_text(encoding="utf-8")

    fm = parse_frontmatter(text)
    if not fm:
        print(f"  ⏭️  No frontmatter — skipping {path.name}")
        return False

    ingredients = fm.get("ingredients")
    if not ingredients:
        print(f"  ⏭️  No ingredients in frontmatter — skipping {path.name}")
        return False

    block = build_table(ingredients, base_servings=fm.get("base_servings", 2))
    new_text = inject_table(text, block)

    if new_text == text:
        print(f"  ✅ Already up-to-date: {path.name}")
        return False

    if dry_run:
        print(f"  📝 Would update: {path.name}")
        # Show a mini diff
        old_lines = text.splitlines()
        new_lines = new_text.splitlines()
        print(f"     {len(old_lines)} → {len(new_lines)} lines")
        return True

    path.write_text(new_text, encoding="utf-8")
    print(f"  ✅ Updated: {path.name}")
    return True


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    args = sys.argv[1:]
    dry_run  = "--dry-run"  in args
    all_mode = "--all"      in args
    paths_raw = [a for a in args if not a.startswith("--")]

    if all_mode:
        paths = sorted(Path("dishes").glob("*.md"))
    elif paths_raw:
        paths = [Path(p) for p in paths_raw if Path(p).suffix == ".md"]
    else:
        print("Usage: scale_ingredients.py [--dry-run] [--all] [file.md ...]")
        sys.exit(1)

    if not paths:
        print("No .md files to process.")
        sys.exit(0)

    print(f"🧮 Processing {len(paths)} file(s){'  [dry-run]' if dry_run else ''}...")
    any_changed = False
    for p in paths:
        any_changed |= process_file(p, dry_run=dry_run)

    if dry_run and any_changed:
        sys.exit(1)  # signal to CI that files are stale


if __name__ == "__main__":
    main()
